In [2]:
import numpy as np

In [1]:
vetor = [1, 3, 9]

type(vetor)

list

In [3]:
meuVetor = np.array(vetor)
meuVetor

array([1, 3, 9])

In [4]:
type(meuVetor)

numpy.ndarray

In [5]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
np.zeros(shape=(4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.random.seed(101)
v1 = np.random.randint(0,100,10)
v1

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [8]:
v2 = np.random.randint(0,100,10)
v2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [9]:
v2.max()

np.int64(93)

In [10]:
v2.min()

np.int64(4)

In [11]:
v2.argmax()

np.int64(8)

In [12]:
v2.argmin()

np.int64(0)

In [13]:
int(v2.mean())

47

In [14]:
v2.shape

(10,)

In [15]:
v2.reshape(5,2)

array([[ 4, 63],
       [40, 60],
       [92, 64],
       [ 5, 12],
       [93, 40]])

In [16]:
matriz = np.arange(0,100)
matriz

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
matriz = matriz.reshape(10,10)
matriz

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [18]:
matriz.shape

(10, 10)

In [19]:
linha = 1
coluna = 2
matriz[linha,coluna]

np.int64(12)

In [20]:
matriz[:,2].reshape(10,1)

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52],
       [62],
       [72],
       [82],
       [92]])

In [25]:
matriz[2,:]

array([20, 99, 99, 99, 24, 25, 26, 27, 28, 29])

In [26]:
matriz[1:3,:]

array([[10, 99, 99, 99, 14, 15, 16, 17, 18, 19],
       [20, 99, 99, 99, 24, 25, 26, 27, 28, 29]])

In [27]:
matriz[1:3,1:4]

array([[99, 99, 99],
       [99, 99, 99]])

In [28]:
matriz[1:3,1:4] = 99
matriz

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 99, 99, 99, 14, 15, 16, 17, 18, 19],
       [20, 99, 99, 99, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])